title = "UnWCF"
# Add an trailing slash to ensure that all fonts render correctly.
baseURL = "https://unwcf.com/"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "unwcf"

# Enable / Disable open link with a new tab.
[blackfriday]
  hrefTargetBlank = true

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = ["css/unwcf.css"]
  js_modules = []

  # Description and meta data for the search engines
  author = "RendleLabs"
  description = "Alternatives to WCF or Windows Communication Foundation"
  keywords = "wcf,soa,microservices,grpc,dotnet,dotnet core,distributed systems"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "E3W2DA5FPS"
  algolia_apiKey    = "5c43206ab881670200e24f180a8da0ac"
  algolia_indexName = "default-content"
    # Set this option to false if you want to search within all articles in all languages at once

    algolia_currentLanguageOnly = true

  # Style configuration
    # set the width of your site's content
    siteWidth = "800px"

    # let hugo automatically resize and crop your images to the correct sizes
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Moving on from Windows Communication Foundation"

    # if you want to use gravatar for the header image
    gravatarEMail = "mark@rendlelabs.com"

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "/images/logo.jpg"

    # define the icon you want to use for the overlay for the customImage or gravatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = false

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    # pinnedPost = "/content/github/"
    # Set to true to pin only to the first page, false to all pages
    # pinOnlyToFirstPage = true

    # enable automatical localization of the article's PublishedDate with momentjs
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = false

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 7

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 7

    # show a language chooser in the footer
    showFooterLanguageChooser = true

    # social media profile urls for the footer links
    showSocialMedia = true

    facebook   = ""
    twitter    = "https://twitter.com/markrendle"
    googleplus = ""
    pinterest  = ""
    instagram  = ""
    tumblr     = ""
    youtube    = ""
    vimeo      = ""
    github     = "https://github.com/RendleLabs"
    xing       = ""
    linkedin   = ""

    # credits line configuration
    copyrightBy = "by RendleLabs"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = ""
    copyrightUrl = "https://github.com/RendleLabs"
    creditsText = "Bilberry Hugo Theme"
    creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"


# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]

